backend:
  name: git-gateway
  repo: "zealzel/papermodZ" # blog 存放在 Github repo 的位置
  branch: "master-cms" # 分支
  site_url: "papermodz-cms.netlify.app" # 你的網站網址

media_folder: "static/img" # 存放多媒體的資料夾
logo_url: /img/out.svg
public_folder: "/img"
locale: "zh_Hant" # 語系 https://github.com/netlify/netlify-cms/tree/master/packages/netlify-cms-locales/src

# npx netlify-cms-proxy-server
local_backend: true

collections: # https://www.netlifycms.org/docs/configuration-options/#collections
  - name: 'posts'
    label: '文章'
    folder: 'content/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: true
    nested:
      depth: 100
      summary: '{{title}}'
    fields:
      - { label: '標題', name: 'title', widget: 'string' }
      #- { label: "AUTHOR", name: "author", widget: "string", default: '{{user.email}'}
          #collection: "authors", 
          #value_field: "name", 
          ##default: '{{user.name}}',
          #default: 'ADF',
          #display_fields: [ "name" ], 
          #search_fields: [ "name", "email" ] 
        #}
      - { label: '發布日期', name: 'date', widget: 'datetime' }
      - { label: "Draft", name: "draft", widget: "boolean", default: true}
      - { label: '摘要', name: 'description', widget: 'string', default: "ABCD111"}
      - { label: '內容', name: 'body', widget: 'markdown' }
      - { label: "標籤", name: "tags", widget: "list", required: false}
      - { label: "分類", name: "categories", widget: "list", required: false}
  - name: authors
    label: Authors
    folder: data/_authors/
    media_folder: ''
    public_folder: ''
    format: json
    create: true
    slug: "{{name}}"
    fields:
      - { label: Name, name: name, widget: string }
      - { label: Title, name: title, widget: string }
      - { label: Email, name: email, widget: string }
      - { label: Shortbio, name: shortbio, widget: text }
      - { label: Image, name: authorimage, widget: image }

